import Head from 'next/head';
import styles from '../styles/Home.module.scss'
import { useRouter } from 'next/router';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.main}>
          <div className={styles.mainHeader}>Simple, fast and secure messenger for your daily routine.</div>
          <div className={styles.mainSubHeader}>No registration or login. The <span>only</span> login information is your device information and IP.</div>
          <Link href="/messenger" className={styles.mainLink}>Start now</Link>
          <div className={styles.mainBubbleBox}>
            <div className={`${styles.mainBubble}`}></div>
            <div className={`${styles.mainBubble} ${styles.mainBubbleLong}`}></div>
            <div className={`${styles.mainBubble} ${styles.mainBubbleShort}`}></div>
          </div>
        </section>
      </main>
    </>
  );
}
